const actionTypes = {
	LOAD_TOKEN_FROM_CACHE: 'LOAD_TOKEN_FROM_CACHE',
	AUTHENTICATE_USER: 'AUTHENTICATE_USER',
	AUTHENTICATE_FAIL: 'AUTHENTICATE_FAIL',
	AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
	LOUGHT_USER: 'LOUGHT_USER',
	
	LOAD_FEATURED_PRODUCTS: 'LOAD_FEATURED_PRODUCTS'
}

export default actionTypes;